# Generated by Django 4.1 on 2022-08-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingGroup',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=64)),
                ('protocol', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
                ('last_touched', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingGroup',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('partner_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=64)),
                ('protocol', models.CharField(max_length=50)),
                ('sitename', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=64)),
                ('last_touched', models.CharField(max_length=64)),
            ],
        ),
    ]
