# Generated by Django 4.1 on 2022-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=64)),
                ('protocol', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
                ('last_touched', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='IncomingGroup',
        ),
        migrations.DeleteModel(
            name='OutgoingGroup',
        ),
    ]
