# Generated by Django 4.1 on 2022-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_incomingfiles_delete_incominggroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingfiles',
            name='file',
            field=models.FileField(upload_to='.'),
        ),
    ]
